server:
  port: 8080

spring:
  application:
    name: flow-boot
  datasource:
    url: jdbc:mysql://localhost:3306/dk-workflow?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

